blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>/', views.tag_page),
    path('category/<str:slug>/', views.category_page),
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view())
]

myblog_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
    path('tmap/', include('tmap.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tmap/urls.py
from django.urls import path
from .views import GeoInformationView, CenterListCreate, CenterListView, ZoneListCreate, VehicleListCreate, \
    OrderListCreate, DispatchListCreate, CenterListUpdate, delete_CenterList, ZoneListView, OrderListView, \
    ZoneListUpdate, delete_ZoneList, VehicleListView, VehicleListUpdate, delete_VehicleList, OrderListUpdate, \
    delete_OrderList, MainListView
from . import views

app_name = 'tmap'

urlpatterns = [
    path('geo/', GeoInformationView.as_view(), name='geo'),
    path('center/insert/', CenterListCreate.as_view(), name='center_insert'),
    path('center/update/<int:pk>/', CenterListUpdate.as_view(), name='center_update'),
    path('center/delete/<int:pk>/', delete_CenterList, name='center_delete'),
    path('center/', CenterListView.as_view()),
    path('zone/insert/', ZoneListCreate.as_view(), name='zone_insert'),
    path('zone/', ZoneListView.as_view()),
    path('zone/update/<int:pk>/', ZoneListUpdate.as_view()),
    path('zone/delete/<int:pk>/', delete_ZoneList),
    path('vehicle/insert/', VehicleListCreate.as_view(), name='vehicle_insert'),
    path('vehicle/', VehicleListView.as_view()),
    path('vehicle/update/<int:pk>/', VehicleListUpdate.as_view()),
    path('vehicle/delete/<int:pk>/', delete_VehicleList),
    path('order/insert/', OrderListCreate.as_view(), name='order_insert'),
    path('order/', OrderListView.as_view()),
    path('order/update/<int:pk>/', OrderListUpdate.as_view()),
    path('order/delete/<int:pk>/', delete_OrderList),
    path('dispatch/', DispatchListCreate.as_view()),
    path('get_marker_data/', views.get_marker_data),
    path('', MainListView.as_view())
]

tmap/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class GeoInformation(models.Model):
    name = models.CharField(max_length=20, null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    def __str__(self):
        return f'{self.name}'


class CenterList(models.Model):
    centerId = models.CharField(max_length=100)
    centerName = models.CharField(max_length=100)
    geo = models.ForeignKey(GeoInformation, null=True, blank=True, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to='tmap/images/center/', blank=True)
    flag = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f'{self.pk} + {self.centerId}'

    def get_absolute_url(self):
        return f'/tmap/center/{self.pk}'


class ZoneList(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=100, null=True)
    flag = models.CharField(max_length=10, null=True)
    type = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return f'/tmap/zone/{self.pk}'


class VehicleDetail(models.Model):
    name = models.CharField(max_length=100, null=True)
    image = models.ImageField(upload_to='tmap/images/vehicle')
    weight = models.FloatField(null=True)
    volume = models.IntegerField(null=True)
    type = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f'{self.name}'


class VehicleList(models.Model):
    vehicleId = models.CharField(max_length=100, null=True)
    vehicleName = models.CharField(max_length=100, null=True)
    vehicleType = models.ForeignKey(VehicleDetail, null=True, blank=True, on_delete=models.CASCADE)
    zoneCode = models.ForeignKey(ZoneList, null=True, blank=True, on_delete=models.SET_NULL)
    skillPer = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], null=True)
    flag = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f'{self.vehicleId}'

    def get_absolute_url(self):
        return f'/tmap/vehicle/{self.pk}'


class OrderList(models.Model):
    orderId = models.CharField(max_length=100, null=True)
    orderName = models.CharField(max_length=100, null=True)
    geo = models.ForeignKey(GeoInformation, null=True, blank=True, on_delete=models.CASCADE)
    serviceTime = models.IntegerField(null=True)
    vehicleType = models.CharField(max_length=10,null=True)
    deliveryWeight = models.CharField(max_length=100, null=True)
    zoneCode = models.ForeignKey(ZoneList, null=True, blank=True, on_delete=models.SET_NULL)
    deliveryVolume = models.CharField(max_length=100, null=True)
    flag = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f'{self.orderId}'

    def get_absolute_url(self):
        return f'/tmap/order/{self.pk}'


class DispatchList(models.Model):
    orderList = models.ForeignKey(OrderList, blank=True, null=True, on_delete=models.CASCADE)
    vehicleList = models.ForeignKey(VehicleList, blank=True, null=True, on_delete=models.CASCADE)
    allocationType = models.CharField(max_length=10, null=True, blank=False)
    startTime = models.CharField(max_length=10, blank=False, null=True)
    optionType = models.CharField(max_length=10, null=True)
    equalizationType = models.CharField(max_length=10, null=True)
    expectedArrivalTime = models.DateTimeField(null=True)
    expectedDepartureTime = models.DateTimeField(null=True)
    start_latitude = models.FloatField(default=0.0)
    start_longitude = models.FloatField(default=0.0)
    end_latitude = models.FloatField(default=0.0)
    end_longitude = models.FloatField(default=0.0)
    vehicleName = models.CharField(max_length=100, null=True)
    orderName = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    mappingKey = models.CharField(max_length=100, null=True)
    flag = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f'{self.pk}'

tmap/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import GeoInformation, CenterList, ZoneList, VehicleList, OrderList, DispatchList
from django.views.generic import CreateView, ListView, UpdateView, TemplateView
import requests
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from PIL import Image


class GeoInformationView(CreateView):
    model = GeoInformation
    fields = ['name']
    template_name = 'tmap/geo.html'
    success_url = reverse_lazy('tmap:geo')

    def form_valid(self, form):
        name = form.cleaned_data['name']

        headers = {
            "Accept": "application/json"
        }
        info = {

            "coordType": "WGS84GEO",
            "fullAddr": name,
        }

        url = f'https://apis.openapi.sk.com/tmap/geo/fullAddrGeo?&coordType={info["coordType"]}&fullAddr={info["fullAddr"]}&appKey=lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx'

        response = requests.get(url, headers=headers)

        response = response.json()
        latitude = response["coordinateInfo"]["coordinate"][0]["lat"]
        if latitude == '':
            latitude = response["coordinateInfo"]["coordinate"][0]["newLat"]

        longitude = response["coordinateInfo"]["coordinate"][0]["lon"]
        if longitude == '':
            longitude = response["coordinateInfo"]["coordinate"][0]["newLon"]

        geo = GeoInformation(name=name, latitude=latitude or None, longitude=longitude or None)

        geo.save()

        alert_script = f"alert('센터 입력 완료!');location.href='{self.success_url}';"

        return HttpResponse(f"<script>{alert_script}</script>")

# CenterList


class CenterListCreate(CreateView):
    model = CenterList
    fields = ['centerId', 'centerName', 'geo']
    template_name = 'tmap/center/center_insert.html'
    success_url = reverse_lazy('tmap:center_insert')

    def form_valid(self, form):
        center = form.save(commit=False)
        geo = center.geo

        latitude = geo.latitude
        longitude = geo.longitude
        centerid = center.centerId
        centername = center.centerName
        address = geo.name
        appkey = "lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx"

        url = f'https://apis.openapi.sk.com/tms/centerInsert?appKey={appkey}&centerId={centerid}&centerName={centername}&address={address}&latitude={latitude}&longitude={longitude}'

        headers = {
            "accept": "application/json",
            "appKey": "e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5"
        }

        response = requests.get(url, headers=headers)
        response = response.json()

        flag = response["resultCode"]
        center.flag = flag


        url = f"https://apis.openapi.sk.com/tmap/staticMap"
        params = {
            'version': 1,
            'appKey': 'lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx',
            'width': '500',
            'height': '300',
            'zoom': '12',
            'longitude': longitude,
            'latitude': latitude,
            'markers': str(longitude)+','+str(latitude)
        }
        response = requests.get(url, params=params)

        image = Image.open(ContentFile(response.content))
        filename = f"static_map_{centername}.jpg"
        path = default_storage.save(f'tmap/images/center/{filename}', ContentFile(response.content))
        center.image = path

        center.save()
        alert_script = f"alert('센터 입력 완료!');location.href='{self.success_url}';"
        return HttpResponse(f"<script>{alert_script}</script>")


class CenterListView(ListView):
    model = CenterList
    template_name = 'tmap/center/center.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['centerList_list'] = CenterList.objects.all().order_by('flag')
        return context


class CenterListUpdate(UpdateView):
    model = CenterList
    fields = ['centerName']
    template_name = 'tmap/center/center_update.html'

    def get_context_data(self, **kwargs):
        context = super(CenterListUpdate, self).get_context_data()
        return context

    def form_valid(self, form):

        center = form.save(commit=False)
        geo = center.geo

        latitude = geo.latitude
        longitude = geo.longitude
        centerid = center.centerId
        centername = center.centerName.encode('utf-8')
        address = geo.name.encode('utf-8')
        flag = center.flag
        appkey = "lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx"
        if flag == "200":
            url = f'https://apis.openapi.sk.com/tms/centerUpdate?appKey={appkey}&centerId={centerid}&centerName={centername}&address={address}&latitude={latitude}&longitude={longitude}'

            headers = {
                "accept": "application/json",
                "appKey": "e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5"
            }

            response = requests.get(url, headers=headers)
            response = response.json()

            flag = response["resultCode"]
            center.flag = flag


        center.save()

        return redirect('/tmap/center/')


def delete_CenterList(request, pk):
    centerList = get_object_or_404(CenterList, pk=pk)
    centerid = centerList.centerId
    appkey = "lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx"
    url = f"https://apis.openapi.sk.com/tms/centerDelete?appKey={appkey}&centerId={centerid}"

    headers = {
        "accept": "application/json",
        "appKey": "e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5"
    }

    response = requests.get(url, headers=headers)

    centerList.delete()
    return redirect('/tmap/center/')


class ZoneListCreate(CreateView):
    model = ZoneList
    fields = ['code', 'name', 'type']
    template_name = 'tmap/zone/zone_insert.html'
    success_url = reverse_lazy('tmap:zone_insert')

    def form_valid(self, form):
        zone = form.save(commit=False)

        name = zone.name
        code = zone.code
        type = zone.type

        if type == "1":
            type="city_do"
        elif type == "2":
            type="gu_gun"
        elif type == "3":
            type="legalDong"
        else:
            type="adminDong"

        appkey = "lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx"
        url = f'https://apis.openapi.sk.com/tms/zoneInsert?appKey={appkey}&code={code}&name={name}'

        headers = {
            "accept": "application/json",
            "appKey": "e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5"
        }

        response = requests.get(url, headers=headers)
        response = response.json()

        flag = response["resultCode"]
        zone.flag = flag
        zone.type = type
        zone.save()

        alert_script = f"alert('권역 입력 완료!');location.href='{self.success_url}';"
        return HttpResponse(f"<script>{alert_script}</script>")


class ZoneListView(ListView):
    model = ZoneList
    template_name = 'tmap/zone/zone.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['zoneList_list'] = ZoneList.objects.all()
        return context


class ZoneListUpdate(UpdateView):
    model = ZoneList
    fields = ['type', 'name']
    template_name = 'tmap/zone/zone_update.html'

    def get_context_data(self, **kwargs):
        context = super(ZoneListUpdate, self).get_context_data()
        return context

    def form_valid(self, form):

        zone = form.save(commit=False)
        name = zone.name
        code = zone.code

        flag = zone.flag
        appkey = "lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx"


        url = f"https://apis.openapi.sk.com/tms/zoneUpdate?appKey={appkey}&code={code}&name={name}"

        headers = {
            "accept": "application/json",
            "appKey": "e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5"
        }

        response = requests.get(url, headers=headers)
        response = response.json()

        flag = response["resultCode"]
        zone.flag = flag

        zone.save()

        return redirect('/tmap/zone/')


def delete_ZoneList(request, pk):
    zoneList = get_object_or_404(ZoneList, pk=pk)
    code = zoneList.code
    appkey = "lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx"
    url = f"https://apis.openapi.sk.com/tms/zoneDelete?appKey={appkey}&code={code}"

    headers = {
        "accept": "application/json",
        "appKey": "e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5"
    }

    response = requests.get(url, headers=headers)

    zoneList.delete()
    return redirect('/tmap/zone/')


class VehicleListCreate(CreateView):
    model = VehicleList
    fields = ['vehicleId', 'vehicleName', 'vehicleType', 'zoneCode']
    template_name = 'tmap/vehicle/vehicle_insert.html'
    success_url = reverse_lazy('tmap:vehicle_insert')

    def get_context_data(self, **kwargs):
        context = super(VehicleListCreate, self).get_context_data()

        return context

    def form_valid(self, form):
        skill_per = self.request.POST.get('skill_per')

        if skill_per == '':
            skill_per = 0

        form.instance.skillPer = skill_per

        vehicle = form.save(commit=False)
        vehicledetail = vehicle.vehicleType
        weight = int(vehicledetail.weight)
        volume = vehicledetail.volume
        zone = vehicle.zoneCode
        vehicle_type = vehicledetail.type
        vehicleid = vehicle.vehicleId
        vehiclename = vehicle.vehicleName

        zone_code = zone.code

        appkey = "lnmQwO8Vzy3E1WkBTNCUv9JWkUEwMQxF4wsCcRjx"

        url = f"https://apis.openapi.sk.com/tms/vehicleInsert?appKey={appkey}&vehicleId={vehicleid}&vehicleName={vehiclename}&weight={weight}&vehicleType={vehicle_type}&zoneCode={zone_code}&skillPer={skill_per}&volume={volume} "

        headers = {
            "accept": "application/json",
            "appKey": "e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5"
        }

tmap/templates/tmap/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tmap - 배차 사이트</title>

    <link href="{% static 'blog/bootstrap/sb-admin-2.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/726bbd6862.js" crossorigin="anonymous"></script>
</head>

<body class="d-flex flex-column min-vh-100" id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Begin of sidebar -->
    {% include 'tmap/sidebar.html' %}
    <!-- End of Sidebar-->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        {% include 'tmap/topbar.html' %}
        <!-- Main Content -->
        <div id="content">

            <div class="container my-3">
                <div class="row">
                    <div class="col-md-8 col-lg-9" id="main-area">
                        {% block main_area %}
                        {% endblock %}

                    </div>


                </div>


            </div>

            <!-- Begin of Topbar -->
            {% include 'tmap/topbar.html' %}
            <!-- End of Topbar -->


            <footer class="py-2 bg-dark mt-auto">
                <div class="container">
                    <p class="m-0 text-center text-white">
                        Copyright &copy; Green Thing
                    </p>
                </div>
                <!-- /.container -->
            </footer>

            <!-- Bootstrap core JavaScript -->
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
                    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
                    crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                    crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
                    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
                    crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>


</body>
</html>

tmap/templates/tmap/base_full_width.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>{% block head_title %}Tmap 배차 사이트{% endblock %}</title>


    <script src="https://kit.fontawesome.com/726bbd6862.js" crossorigin="anonymous"></script>
    <link href="{% static 'blog/bootstrap/sb-admin-2.css' %}" rel="stylesheet">
</head>

<body>


<div id="wrapper">
    {% include 'tmap/sidebar.html' %}

    <div id="content-wrapper" class="d-flex flex-column">
        {% include 'tmap/topbar.html' %}
        <div class="container my-3">
            <div class="row">
                <div class="col-12" id="main-area">
                    {% block main_area %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="py-2 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
</footer>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>

tmap/templates/tmap/center.html
{% extends 'tmap/base.html' %}
{% block main_area %}
    {% load crispy_forms_tags %}
    <div align="center">
        <h2>CenterList</h2>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>

            {{ form | crispy }}

        </table>
        <button type="submit" class="btn btn-success float-right">Submit</button>
    </form>
    </div>

{% endblock %}

tmap/templates/tmap/center_get.html
{% for c in centerlist_list %}

<div class="card mb-4">
    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
    <div class="card-body">
        <p class="card-title">{{ c.centerId }}</p>
        <p class="card-text">{{ c.centerName }}</p>
        <p class="card-text">{{ c.geo }}</p>

    </div>
</div>
{% endfor %}

tmap/templates/tmap/geo.html
{% extends 'tmap/base.html' %}

{% block main_area %}
<div>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

tmap/templates/tmap/main.html
{% extends 'tmap/base_full_width.html' %}

{% block main_area %}

<style>
  .scrollable-list {
    max-height: 300px; /* 원하는 최대 높이로 조정하세요 */
    overflow-y: auto;
  }


</style>

<div class="container">
    <div class="row">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Featured
            </div>
            <div class="scrollable-list">
                <ul class="list-group list-group-flush">
                    {% for z in zoneList %}
                    <li class="list-group-item">{{z}}</li>
                    {% endfor %}

                </ul>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Featured
            </div>
            <div class="scrollable-list">
                <ul class="list-group list-group-flush">
                     {% for c in centerList %}
                    <li class="list-group-item">{{c}}</li>
                     {% endfor %}

                </ul>
            </div>


        </div>

    </div>

</div>

<div class="container">
    <div class="row">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Featured
            </div>
            <div class="scrollable-list">
                <ul class="list-group list-group-flush">
                   {% for o in orderList %}
                    <li class="list-group-item">{{o}}</li>
                    {% endfor %}

                </ul>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Featured
            </div>
            <div class="scrollable-list">
                <ul class="list-group list-group-flush">
                    {% for v in vehicleList %}
                    <li class="list-group-item">{{v}}</li>
                    {% endfor %}

                </ul>
            </div>


        </div>

    </div>

</div>

{% endblock %}

tmap/templates/tmap/topbar.html
{% load socialaccount %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>



    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                               placeholder="Search for..." aria-label="Search"
                               aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-success" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>






    </ul>

</nav>